### ISSUE TITLE
stats exception

### ISSUE THREAD

**Issue by illogicalextend** [ArkEcosystem/arky#17]
Every now and then I encounter this. Not sure of the cause, could be a http interruption but it seems to result in tx_in not being complete (half a list?). Not sure why the exception doesn't get handled based on the catches. 

> arky/util/stats.py", line 51, in getHistory
> return sorted([t for t in tx_in if t["timestamp"] >= timestamp], key=lambda e:e["timestamp"], reverse=True)
> TypeError: string indices must be integers, not str

**Comment by devxa** [comment]
Might it be possible that api.Transaction.getTransactionsList() returns a dictionary in some cases?
In such case, the comprehension list in the return would iterate through the keys of the dictionary yielding an error.

If this is causing the issue then a solution can be just placing this before the return:
`if type(tx_in) == dict:
    tx_in = [tx_in]`

**Comment by illogicalextend** [comment]
I don't understand why the code didn't Except on the following, as it wouldn't be a populated list:

> if isinstance(tx_in, list) and len(tx_in):
> ..
> else:
> raise Exception(tx_in.get("error", "Api error"))

**Comment by Moustikitos** [comment]
Which python version do you use ?

**Comment by illogicalextend** [comment]
2.7.3. I guess the line of code will be where getHistory is called.

**Comment by Moustikitos** [comment]
this error occur when API did not respond. Will dive in code to catch it correctly.
