### ISSUE TITLE
Arky breaks logging

### ISSUE THREAD

**Issue by florensie** [ArkEcosystem/arky#70]
When used together in a Flask project in my case arky prevents the logging from working.

**Comment by florensie** [comment]
I can see stack traces but not the requests made to webpages. I saw that arky uses the 'requests' logger but I don't think Flask/Werkzeug does.

**Comment by Moustikitos** [comment]
hi,

first thanks for the report. Arky use logging to write data. Logging to request package is set to critical in arky package initialisation file : 
https://github.com/ArkEcosystem/arky/blob/aip11/arky/__init__.py#L26

if you want to get back logging from requests package in your Flask app, just ask it : 
```python
import logging
logging.getLogger('requests').setLevel(logging.INFO)
```

**Comment by florensie** [comment]
It still won't work with a simple test like this:
```
from flask import Flask
import arky.rest
import logging

app = Flask(__name__)
arky.rest.use('ark')
logging.getLogger('request').setLevel(logging.DEBUG)


@app.route('/')
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    app.run()
```

**Comment by Moustikitos** [comment]
Do you have a `.arky` file ? Logging is redirexted to this file.

**Comment by florensie** [comment]
That seems to have fixed it thanks. The colors don't work anymore but that isn't a huge issue. I feel like arky shouldn't have interfered with flask in the first place though.

**Comment by Moustikitos** [comment]
Okay, try import `arky` before `Flask`.

to shut arky loggin : 
```python
logging.getLogger('arky').setLevel(logging.CRITICAL)
```
