### ISSUE TITLE
Switch to pipenv and add linting to travis build

### ISSUE THREAD

**Issue by rodxavier** [ArkEcosystem/arky#81]
I was thinking if adding pipenv would be a welcome addition. Basically, this will replace `requirements.txt` with a `Pipfile` and `Pipfile.lock`. It would also be easier to separate packages only used for development to packages used by the library.

In CI, this will also allow us to run `pipenv check` which checks for vulnerabilities of the dependencies.

I was also thinking if installing a linter like flake8 would be good to keep the code clean and maintainable.

I'll be keen to work on this if it will be a good addition to the library.

**Comment by roks0n** [comment]
I've never used pipenv before, but it really cool. Also, I think adding a lint check (only on the diff) would be useful, especially if (and when) there are more people working on a project. I guess we would just need to specify which pep8 standards do we want Arky to follow and which not.

**Comment by Moustikitos** [comment]
Sounds nice because it is recommended. I'm okay with that !

**Comment by rodxavier** [comment]
I'll start working on this and submit a PR.

**Comment by Moustikitos** [comment]
Nice !
