### ISSUE TITLE
Follow PEP 8 standard

### ISSUE THREAD

**Issue by rodxavier** [ArkEcosystem/arky#83]
As raised by @roks0n, I think we should start following pep 8 standards.

This is the output of running `flake8 arky test`. Most of the stuff are pretty trivial.

[arky_flake8.txt](https://github.com/ArkEcosystem/arky/files/1722237/arky_flake8.txt)

We should also make a decision on tabs vs spaces. I can see that some files use tabs and some use spaces.
Personally, I use 4 spaces per indent.

**Comment by roks0n** [comment]
I think I'm the culprit for those spaces. 🙈 Based on our decision I can change that later.

Your output also seems to be missing `I100 Imports statements are in the wrong order.`

**Comment by Moustikitos** [comment]
I love so much tabs ! Tab and space are PEP8 compliant... i know space are recommended, but tab is cleaner to me (les chars :) )

**Comment by rodxavier** [comment]
I don't mind using tabs as long as we use it consistently throughout the repo. 😃

**Comment by Moustikitos** [comment]
okay... **TABS**
